name: display
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  camera: ^0.11.0+2
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_tts: ^4.0.2
  image_gallery_saver: ^2.0.3
  usb_serial: ^0.5.2

dev_dependencies:
  build_runner: ^2.4.11
  lints: ^3.0.0
  mockito: ^5.4.4
  test: ^1.24.0
